### ISSUE TITLE
Улучшить тесты

### ISSUE THREAD

**Issue by Monnoroch** [Monnoroch/blerpc-android#15]
Блок кода, игнорирующий обновление после отписки протестирован тестом `testValueChangedAfterReset`. Это не правильно:

1. Reset тут вообще ни при чем.
2. Там два if и нужно два теста. Конкретных теста на именно эти ситуации, а не reset.

**Comment by AseevEIDev** [comment]
Если ты имеешь ввиду блок кода:
`if (status == subscribing || unsubscribing) return;`
То тесты `testValueChangedBeforeOnDescriptorWriteSubscribe` и `testValueChangedBeforeOnDescriptorWriteUnsubscribe` проверяют эти ситуации

**Comment by Monnoroch** [comment]
Странно, в оригинальном PR я не нашел их.

**Comment by Monnoroch** [comment]
А, я разобрался. Вот это условие `!subscriptions.containsKey(characteristicUuid)` ты тестируешь с помощью `testValueChangedAfterReset`. Это слишком грубый тест, надо отключить именно эту подписку, а не все прибить. И имя подобрать соответствующее.

**Comment by AseevEIDev** [comment]
Не получится просто отключить подписку, `subscriptions.clear()` вызывается только в методе `reset()`, а `subscriptions.remove()`, только при ошибке при подписке. Таким образом эта ошибка будет вылезать только, если мы сделаем `reset()`

**Comment by Monnoroch** [comment]
Что-то я не верю. Когда мы отписываемся, подписка удаляется. Следственно, можно ее удалить и потом послать событие.

**Comment by AseevEIDev** [comment]
Просто сделай поиск "subscriptions" по файлу и посмотри в каких методах вызывается clear(). remove().

**Comment by Monnoroch** [comment]
Верно, но вот есть строка: `subscription.status = SubscriptionStatus.UNSUBSCRIBED;`. Кажется, что после нее очень можно поставить комментарий `// New rpc calls might have been added since we started unsubscribing.`, и поставить:
```
        subscription.clearCanceled();
        if (!subscription.hasAnySubscriber()) {
            subscriptions.remove(...)
            return;
        }
```

**Comment by AseevEIDev** [comment]
С этим согласен, тоже хотел, но не успел предложить очищать subscriptions, после unsubscribe. Следующим PR добавлю эти строки, напишу на них тест и + изменю тест, о котором в этой задаче шла речь
