### ISSUE TITLE
Контроль версий модулей

### ISSUE THREAD

**Issue by AseevEIDev** [Monnoroch/blerpc-android#47]
В данный момент команда bintrayUpload запусткает по очереди аплоад каждого из наших модулей по очереди. Если загрузка одного из модулей не пройдет, то другие модули загружены точно не будут, потому что цепочка прервется.

В какой ситуации может быть ошибка - когда модуль с такой же версией уже загружен в JCenter(). Таким образом если мы сделали изменения и изменили версию только у reactive-blerpc, то он загружен в JCenter() не будет, так как версия blerpc не изменилась и она остановит всю цепочку.

Первой мыслью было использовать флаг override, который появился буквально 2 недели назад в новом обновлении либы для Upload. Но это плохо, вдруг мы забудем поменять версию и тогда у пользователей просто обновится модуль, хотя они версию не меняли.

Таким образом на данный момент единственным работающим решением является запуск bintrayUpload для каждого модуля отдельно:

```
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then
          gradle blerpc:bintrayUpload -PbintrayUser=monnoroch -PbintrayKey="$BINTRAY_API_KEY" -PdryRun=false;
          gradle blerpcproto:bintrayUpload -PbintrayUser=monnoroch -PbintrayKey="$BINTRAY_API_KEY" -PdryRun=false;
          gradle reactive-blerpc:bintrayUpload -PbintrayUser=monnoroch -PbintrayKey="$BINTRAY_API_KEY" -PdryRun=false;
    fi
```

**Comment by Monnoroch** [comment]
Я не понимаю чего-то наверное, но у нас версия одна на все компоненты. Как может случиться, что

> так как версия blerpc не изменилась и она остановит всю цепочку.

?

**Comment by AseevEIDev** [comment]
Очень просто. 

1) У нас blerpcproto живет отдельно. Вначале мы повышаем у нее версию, потом она заливается в JCenter(), после этого мы ее добавляем в  зависимостях к blerpc.
2) При добавлении нового модуля, как сейчас. Мы добавили плагин, но сам blerpc не изменился. В будущем мы будем добавлять еще валидаторы и т.д.

**Comment by Monnoroch** [comment]
А что будет, если плагин и blerpc зависят от разных версий blerpcproto? Ничего хорошего. Потому надо сделать какую-то унифицированную сборку, чтоб все было максимально равномерно и чтоб нельзя было сделать разные версии пакетов.

**Comment by AseevEIDev** [comment]
Для этого мы создали константу в project::gradle, которая не дает нам прописывать разные версии у Blerpc и reactive-blerpc.
```
ext {
    blerpcVersion = '0.2.2'
}
```

Предлагаю тут добавить `blerpcproto = `0.2.2`, таким образом мы не сможем в blerpc и reactive-blerpc использовать разные версии blerpcproto

**Comment by Monnoroch** [comment]
Да. Еще убедись, что плагин зависит от blerpc:${blerpcVersion}.

**Comment by Monnoroch** [comment]
А, блин, это тоже же не сработает, ведь плагин надо обновлять тоже отдельно от blerpc.

Что насчет сделать сборку в CI с локального кода, без скачивания пакетов?

**Comment by AseevEIDev** [comment]
> А, блин, это тоже же не сработает

Сработает, эта переменная будет использоваться только для подключения в blerpc:gradle и reactive-blerpc:gradle. 

> Что насчет сделать сборку в CI с локального кода, без скачивания пакетов?

Не получится, Proguard в релизной сборке ругаться будет. Это же основная причина всех наших бед с версиями

**Comment by Monnoroch** [comment]
> Сработает
Не сработает. Та же ситуация у нас с blerpc-плагином. Нельзя их редактировать в одном PR.

**Comment by Monnoroch** [comment]
> Не получится

На что он будет ругаться?

**Comment by AseevEIDev** [comment]
А мы их и не будем редактировать в одном PR. Мы обновляем blerpcproto, а в blerpc и reactive-blerpc ничего не меняется, там будет из JCenter подгружаться предыдущая версия blerpcproto

**Comment by Monnoroch** [comment]
> там будет из JCenter подгружаться предыдущая версия blerpcproto

Вот именно. И поэтому мы не будем уверены, что все работает.

**Comment by AseevEIDev** [comment]
> На что он будет ругаться?

Чтобы у нас в приложении мы могли сделать import blerpc.proto, нужно протобуфный файл держать в отдельной чисто Java либе, так как protobuf-gradle-plugin не достает proto файлы из андройдовских .aar пакетов.

Таким образом у нас в Gradle 2 импорта: blerpc и blerpcproto.
Если в Blerpc мы подключаем Blerpcproto локально, не через JCenter(), то Gradle не видит, что BleRpc из JCenter() - это та же лита, которая подключена к BleRpc локально. И при релизной сборке он ругается - Dublicate Zip Entry. Если мы подключаем к BleRpc протобуфный файл через JCenter(), то Gradle видит, что это одна и та же либа и ругаться не будет

**Comment by AseevEIDev** [comment]
Я не могу не дублировать, мне нужно в приложении подключить BleRpcProto из JCenter() отдельно, сдублировав, потому что 
> нужно протобуфный файл держать в отдельной чисто Java либе, так как protobuf-gradle-plugin не достает proto файлы из андройдовских .aar пакетов.

**Comment by Monnoroch** [comment]
Мда. Ладно, пусть будет как ты придумал.

**Comment by AseevEIDev** [comment]
> Предлагаю тут добавить blerpcproto = 0.2.2

Для ясности нужно иметь 2 переменных
```
ext {
    blerpcVersion = '0.2.2'
    blerpcprotoJCenterVersion = '0.2.2'
    blerpcprotoVersion = '0.2.3'
}
```

**Comment by AseevEIDev** [comment]
`blerpcprotoJCenterVersion` будет использоваться для подключения в blerpc и reactive-plugin
`blerpcprotoVersion` версия либы в нашем репозитории, которая обновляется раньше и может временно быть выше

**Comment by Monnoroch** [comment]
Тогда blerpcVersion тоже должно быть две штуки.

**Comment by AseevEIDev** [comment]
Не должно, blerpc мы в других модулях не используем, поэтому эта переменная не нужна

**Comment by Monnoroch** [comment]
Мы используем его в плагине, нет?

**Comment by AseevEIDev** [comment]
blerpcprotoJCenterVersion - это как в dockerfile хэш коммита для линтеров. Линтеры могут обновиться, но мы будем использовать ту версию, которую указали.

**Comment by AseevEIDev** [comment]
> Мы используем его в плагине, нет?

Нет, плагин от BleRpc не зависит, только от BleRpcProto

**Comment by AseevEIDev** [comment]
Тесты для плагина зависят, но там BleRpc подключается локально. И если мы BleRpc обновили, то тесты плагина упадут и мы не пропустим эту ошибку, что BleRpc обновили, а плагин нет

**Comment by Monnoroch** [comment]
При чем тут это? Мы используем blerpc в плагине, значит, должна быть отдельно версия blerpc в jcenter и отдельно используемая в плагине.

**Comment by AseevEIDev** [comment]
Секунду, я как пользователь хочу подключить себе BleRpc с плагином. Значит это должно быть так:
```
ext {
    blerpcVersion = '0.2.2'
}
dependencies {
  compile "com.github.monnoroch:blerpc-android:${blerpcVersion}"
  compile "com.github.monnoroch:blerpcproto-android:${blerpcVersion}"
  compile "com.github.monnoroch:reactive-blerpc:${blerpcVersion}"
}
```

Соответственно возможна такая ситуация, что версия blerpc 0.2.3 уже вышла, а плагин этой версии еще не вышел. Поэтому да, ты прав, все модули должны быть независимы друг от друга и копилироваться и собираться тоже отдельно, если их вырезать из нашего репозитория.

Это значит, что:
- reactive-blerpc имеет свою переменную version, которая ровняется последней версии плагина
- blerpc имеет свою version, которая ровняется последней версии blerpc
- blerpcproto имеет свою version

Структура зависимостей такая: reactive-blerpc -> blerpc -> blerpcproto
