### ISSUE TITLE
Do not ignore errors on cancelled subscriptions

### ISSUE THREAD

**Issue by Monnoroch** [Monnoroch/blerpc-android#6]
Context: https://github.com/Monnoroch/blerpc-android/blob/2d9a52b9abd0d0a4e69ff70321ec3637d00a41ab/blerpc/src/main/java/com/blerpc/BleRpcChannel.java#L706. Now I'm thinking these should not be ignored: the user is free to ignore them if needed, but the library should not hide errors.

**Comment by AseevEIDev** [comment]
По моему мнению запрос на девайс можно сравнить с запросом на сервер с помощью gRPC или Retrofit. Когда мы начали запрос и решили его отменить - было бы очень странно получить ошибку, после отмены и думать еще и как ее избежать. Я не могу предположить не одного варианта, когда нам нужна будет ошибка, после того, как мы уже отменили запрос.

Учитывая, что эта библиотека открытая и ее возможно будем использовать не только мы, то я на месте пользователя либы очень бы удивился, как такое может быть, тем более, что этот случай рандомный и далеко не каждый раз всплывет ошибка, из-за чего ее просто можно пропустить и она вылезет, когда не должна. Мы введем в ступор 99% пользователей этой ситуацией, потому что вдруг 1% понадобится получить эту ошибку допустим для статистики.

Поэтому мне кажется, что нам стоит взять пример  с gRPC, Retrofit и не допускать ситуации, когда может прийти ошибка, после отмены запроса. Если пользователю либы вдруг понадобится эта информация, то код открытый, он легко может такие мелочи доделать под себя.

**Comment by Monnoroch** [comment]
> Я не могу предположить не одного варианта, когда нам нужна будет ошибка

Я могу -- репорт проблем.

> Мы введем в ступор 99% пользователей этой ситуацией

RTFM и все будет хорошо.

> и не допускать ситуации, когда может прийти ошибка, после отмены запроса.

Невозможно сделать: API протобуфных сервисов не позволяет.

> он легко может такие мелочи доделать под себя

Ха-ха, много ли раз под себя ты доделывал сложный софт? Нет, это плохая стратегия.

**Comment by Monnoroch** [comment]
В итоге нет, то, что ты хочешь, сделать на 100% невозможно. С очень малой вероятностью ошибки все равно будут приходить, даже если это "запретить". Следственно, пользователь должен в любом случае их обрабатывать, следственно, уж лучше мы ему их отдадим все, а там он разберется.

**Comment by AseevEIDev** [comment]
> С очень малой вероятностью ошибки все равно будут приходить, даже если это "запретить".

Согласен, в данном случае возможен вариант, что мы отпишемся в ту миллисекунду, когда пройдет проверка `ifNotCanceled()`, а проследить, чтобы эта проверка и отписка проходили в одном потоке - нереально. 

Поэтому я удаляю аналогичную проверку и для подписок, пусть ошибки приходят тогда все
