### ISSUE TITLE
Тест на возвращение ошибки observer-у, если во время запроса был diconnect.

### ISSUE THREAD

**Issue by pffan91** [Monnoroch/blerpc-android#68]
Из диалога:

```
И тут написать документацию, что мы не возвращаем error потому, что на саомом деле она по другому каналу вернется, с указанием имени теста, который это проверяет.
```

Related: https://github.com/Monnoroch/blerpc-android/pull/66#discussion_r289983669

**Comment by Monnoroch** [comment]
Эта задача не нужна. Тестов будет много и тесты будут в том же PR, что и код, как и полагается тестам.

**Comment by pffan91** [comment]
Так я TODO поставил в коде, необхоидмо указать номер задачи

**Comment by Monnoroch** [comment]
Так не надо ставить никаких туду, надо сразу же и сделать.

**Comment by pffan91** [comment]
Ну все же давай сначала  мы доделаем сам воркер, а потом обнесем его тестами. Завтра вдруг придумаем еще что то и не хочется переписывать тесты..

**Comment by Monnoroch** [comment]
Тесты пишутся в том же PR, что и код, код без тестов в мастер не мержится.
