### ISSUE TITLE
Нужно уведомлять об успешной подписке на BLE характеристику

### ISSUE THREAD

**Issue by AseevEIDev** [Monnoroch/blerpc-android#7]
В данный момент `BleRpcChannel` устроен таким образом, что при подписке на характеристику невозможно узнать, прошла ли подписка успешно, пока не придет первое значение.

Пример: мы подписались на батарею, но девайс пришлет нам значение, только когда изменится процент, что может случиться допустим через 20 секунд. А это значит, что 20 секунд мы не будем знать, подписка на характеристику в процессе или мы уже подписались.

Особенно критично это в тех ситуациях, когда мы должны точно знать, что подписка активна. Примером служит обновление прошивки девайса. Мы должны подписаться на получение номеров блоков файлы прошивки, которые нужно послать на девайс и только после этого посылать метаданные образа прошивки.

Варианты решений:
1) В `onDescriptorWrite()` мы получаем коллбэк о том, что подписка прошла успешно, а в `onCharacteristicChanged()` мы получаем уже значения по этой подписке и посылаем их подписчику. 
Нам нужно при успешной подписке, о чем мы узнаем в `onDescriptorWrite()`, сразу же отправить подписчику пустой `Message`, чтобы его уведомить о том, что все ок. Для этого в начало метода `BleRpcChannel#185 handleSubscribe()`, который вызывается при успешной подписке, нужно добавить следующий код

```java
private void handleSubscribe(BluetoothGattCharacteristic characteristic, byte[] value) {
    RpcCall call = calls.getFirst();
    call.done.run(call.responsePrototype.getDefaultInstanceForType());
    ...
}
```

А подписчик (приложение) уже сам решит, игнорировать ему первое пустое значение по подписке или же обработать его, чтобы понять, что подписка активна.

2) Создать `SubscribtionBleRpcController extends BleRpcController`, в который добавить + 1 абстрактный метод `onSubscribeSuccess()`. И если мы используем именно `SubscribtionBleRpcController` при создании запроса, то `BleRpcChannel` вызовет этот коллбэк при успешной подписке. В начало метода` BleRpcChannel#185 handleSubscribe()`, который вызывается при успешной подписке нужно добавить следующий код

```java
private void handleSubscribe(BluetoothGattCharacteristic characteristic, byte[] value) {
    BleRpcController controller = calls.getFirst().controller;
    if (controller instanceOf SubscriptionBleRpcController) {
        ((SubscriptionBleRpcController) controller).onSubscribeSuccess();
    }
    ...
}
```

Преимущество еще и в том, что подписчик (приложение) может сам решить нужен ему коллбэк при успешной подписке или нет.

**Comment by Monnoroch** [comment]
1. Костыль. Нельзя по каналу для ответов сервера отдавать какие-то "вспомогательные" обьекты -- приложение никак не может определить, вспомогательный этот обьект или нет. Так мы никогда не будем делать.

2. Идея любопытная. Да, думаю, можно сделать что-то такое. Но надо подумать, как именно. Твой вариант -- явно не единственный. Можешь набросать список всего, что придумается за пару дней?

**Comment by Monnoroch** [comment]
Насчет (2) -- тут явно недоразработанная идея. Единственный ли это нужный коллбэк? А что насчет отписки? А что насчет других методов? Думаю, тут нужен небольшой дизайн продумать.

**Comment by AseevEIDev** [comment]
Согласен, 1й вариант оставил для сравнения, определенно 2й вариант нужно использовать. Я конечно же продумаю, какие коллбэки могут еще быть. Учитывая, что это отдельная либа, то коллбэки должны быть на все, что может быть полезно и на отписку в том числе.

Но переписывать все методы не хочется, поэтому я не буду их делать абстрактными, а просто пустыми, а пользователь уже сам по желанию перепишет те, которые ему нужны.

Как считаешь, может отдельный `SubscribtionBleRpcController` не делать, а просто все коллбэки пустыми методами добавить в существующий `BleRpcController` или лучше не мешать все в одно, хочешь переписывать методы для подписки, используй `SubscribtionBleRpcController`?

**Comment by Monnoroch** [comment]
> а просто все коллбэки пустыми методами добавить в существующий

Вполне разумная идея, да.

**Comment by AseevEIDev** [comment]
В данный момент для READ, WRITE, SUBSCRIBE нужно добавить следующие коллбэки:
- onSubscrubeSuccess()
- onUnsubscribeSuccess()

На данный момент помимо этих коллбэков все необходимое уже есть.

Нам желательно еще сделать запросы для RSSI, MTU, но это коллбэков уже не касается - https://github.com/Monnoroch/blerpc-android/issues/8

**Comment by AseevEIDev** [comment]
В данный момент в BleRpcChannel сделать коллбэк `onUnsubscribeSuccess()` не получится:
- у нас может быть 2 подписки на допустим батарею и если мы отпишемся, то останется еще одна подписка и все `onUnsubscribeSuccess()` не будет вызван, потому что подписка на BLE характеристику все равно остается
- если подписок нет, то создается отдельный RpcCall с контроллером равным null. Таким образом запрос на отписку никак не относится к запросу подписки

**Comment by Monnoroch** [comment]
Та же ситуация и с подпиской. Подписка на метод != подписка на BLE-характеристику. А именно, подписаться на метод можно 100 раз, а подписка на BLE-характеристику будет одна все равно. В #12 ты делаешь коллбэк на подписку на характеристику, а не на метод, а это неинтуитивно.

**Comment by AseevEIDev** [comment]
Да, согласен, если подписка уже активна, то коллбэк не придет. А значит:
- при вызове нужно проверить есть ли такая уже подписка и если да, то кинуть коллбэк сразу
- нужно уточнить в доке, что подписка на BLE характеристику

**Comment by Monnoroch** [comment]
> нужно уточнить в доке, что подписка на BLE характеристику

Не нужно, ведь ты будешь кидать успех сразу же, если уже есть подписка на характеристику.
